### ISSUE TITLE
검색창 관련 이슈 발생

### ISSUE THREAD

**Issue by billy5982** [For-The-Dev/Interview-Defence-Go-Client#16]
- [x] 타이핑 시 인풋창과 연동이 되지 않아 실시간 검색에 연동이 되지 않음 
- [x] 아무 단어나 입력해도 추가되는 현상 발생

**Comment by billy5982** [comment]
아무 단어나 입력해도 추가되는 현상 발생에 대해  만약 스택이 존재하지 않는 경우에는 실시간 검색창에 'state'로 인터뷰 진행하기
이런 느낌을 추가하는 게 어떨까합니다

**Comment by billy5982** [comment]
#21 확인 부탁드립니다!
요약
```
Stack 인풋창에 입력 시 연관 검색 관련 후보군이 줄어들지 않는 에러
Stack 입력값이 선택한 값과 동일하지만 대소문자로 인해 스택이 중복되는 문제 발생
Stack 선택 이후 Focus가 유지되어 연관 검색 관련 후보군이 표시되지 않는 문제 발생
사용자가 후보군에 없는 Stack 입력 시 연관 검색 후보군엔 도움말이 표시되지 않아 '입력한 스택'으로 시작하기 라는 항목 추가
```

**Comment by OneMoreBottlee** [comment]
확인했습니다 ! 고생많으셨어요 !!!

2, 3, 4번의 경우에는 생각도 못한 에러였는데 역시 명규님입니다..!
