### ISSUE TITLE
프로필 관련 이슈 사항

### ISSUE THREAD

**Issue by billy5982** [For-The-Dev/Interview-Defence-Go-Client#17]
- [x] 오늘의 답변의 개수와 프론트측 day.js를 이용한 시간이 정확하지 않음
       - 아마 db에 createdAt이 UTC +00:00으로 저장되는 것과 연관이 있어보임.
       - 단 프론트 측 날짜는 day.js 의 문제임을 확인함.
       - 클라이언트와 서버 같이 확인 예정

**Comment by billy5982** [comment]
#23 pr에 해결내용 올려놨습니다

**Comment by OneMoreBottlee** [comment]
확인 후 머지했습니다 고생하셨습니다 !!
